ANPR
marsiitr/Automatic-Number-Plate-Recognition pull request #5
Opened 2020-07-28 19:37 UTC by atharva2702

2020-07-28 19:58 UTC, SanjeevKrishnan requested changes
@atharva2702 @kush1920 Changes Required
1. Remove all tmp.md file
2. CAD Images have to be present inside Mechanical Design folder. Upload other project related pictures in Images folder.
3. Rename "anpr.jpg" as "Poster.jpg"
4. Justify text in Report.
5. workflow.jpg has to be present inside Images and Videos/Images.
6. In README.md, Cost Structure should be a H2 type heading.
7. In README.md, hyperlink Team Members and Mentors names with their GitHubprofile link.

2020-07-29 05:24 UTC, Shubhanshu07 commented on README.md
> +## Limitations
@atharva2702 
This should be lists

2020-07-29 05:25 UTC, Shubhanshu07 commented on README.md
> +## Future Improvement
This should be  in list.

2020-07-29 05:25 UTC, Shubhanshu07 commented on README.md
> +## Applications
use Unordered list for them also.

2020-07-29 09:14 UTC, SanjeevKrishnan requested changes
@atharva2702 Changes Required
1. Alignment is not proper in the report. Fix it
2. In README.md, use `<p align="justify">Content<\p>` to justify the text, where content is the text you want to justify.

2020-07-29 13:00 UTC, SanjeevKrishnan approved these changes
@atharva2702 @kush1920 All requirements are met!
@Shubhanshu07 I suggest for merge!

2020-07-29 16:40 UTC, Shubhanshu07 commented
@atharva2702 Great Work GUYS..!!
Merging it

2020-07-29 16:40 UTC, merged